# Generated by Django 5.0.2 on 2025-07-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_affiliateproduct_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateproduct',
            name='temp',
        ),
    ]
