# Generated by Django 5.0.2 on 2025-07-13 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_affiliateproduct_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
