# Generated by Django 5.0.2 on 2025-07-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eye_delete_click'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eye',
            new_name='ProductClick',
        ),
    ]
