# Generated by Django 5.0.2 on 2025-07-18 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_eye_productclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='cons',
            field=models.TextField(blank=True, help_text='Product disadvantages (one per line)'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this product review'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='pros',
            field=models.TextField(blank=True, help_text='Product advantages (one per line)'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='review_content',
            field=models.TextField(blank=True, help_text='Detailed review content for AdSense'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='review_published',
            field=models.BooleanField(default=False, help_text='Publish the review'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='review_summary',
            field=models.TextField(blank=True, help_text='Brief summary of the review'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='review_title',
            field=models.CharField(blank=True, help_text='SEO-friendly review title', max_length=300),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=300),
        ),
    ]
