# Alternative simple nixpacks configuration
# Use this if the main nixpacks.toml doesn't work
# To use: mv nixpacks.toml nixpacks.backup.toml && mv nixpacks.simple.toml nixpacks.toml

providers = ["python"]

[variables]
PYTHON_VERSION = "3.11"

[start]
cmd = "python manage.py migrate --noinput && python manage.py create_superuser_from_env --skip-if-exists && gunicorn amazon.wsgi"
