# Alternative simple nixpacks configuration
# Use this if the main nixpacks.toml doesn't work
# To use: mv nixpacks.toml nixpacks.backup.toml && mv nixpacks.simple.toml nixpacks.toml

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate --noinput && python manage.py create_superuser_from_env --skip-if-exists && gunicorn amazon.wsgi"
