[phases.setup]
# No custom setup needed

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn amazon.wsgi --chdir amazon" 