[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "bash deploy.sh && gunicorn amazon.wsgi"
