[phases.build]
cmds = [
  "python manage.py --version || (echo 'Python failed to run' && exit 1)"
]

# Note: Railway will use Procfile for deployment commands
# This nixpacks.toml is kept for potential alternative deployment methods